# Configuración para base de datos distribuida REAL en múltiples computadoras
# IMPORTANTE: Cambia las IPs por las IPs reales de tus computadoras

[[shards]]
name = "Pereira"
idx = 0
address = "10.1.2.4:8080"   # PC físico - IP pública
replicas = []

[[shards]]
name = "Medellin"
idx = 1
address = "10.1.0.4:8080"       # VM Medellín - IP privada
replicas = []

[[shards]]
name = "Cali"
idx = 2
address = "10.1.1.4:8080"       # VM Cali - IP privada
replicas = []
